### ISSUE TITLE
Analyze requests volume vs. temperature

### ISSUE THREAD

**Issue by apanella** [dssg/411-on-311#1]
- Code to visualize/analyze 3-1-1 requests vs. daily temperature (big database)

**Comment by jpvelez** [comment]
Better to break each to do into a separate issue that you can close with a commit.

On Tue, Jun 25, 2013 at 8:49 AM, apanella <notifications@github.com="mailto:notifications@github.com">> wrote:
• Code to visualize/analyze 3-1-1 requests vs. daily temperature (big database)
  • Make the existing code working on EC2 (upload open portal 311 tables and make paths absolute)
  • ??
