### ISSUE TITLE
Cursory K-Clustering!

### ISSUE THREAD

**Issue by SarahAdelaide** [dssg/411-on-311#5]

**Comment by SarahAdelaide** [comment]
Scott did this with Python! Thank you Scott.

**Comment by jpvelez** [comment]
Please refer to relevant commit when closing issues. Ask @hunterowens about how to do this.

**Comment by SarahAdelaide** [comment]
There is no relevant commit in this case.

**Comment by jpvelez** [comment]
Why not? Where is the script that does the k-clustering?
